// <auto-generated />
namespace e_mandi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_unique_key_to_surveyno : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_unique_key_to_surveyno));
        
        string IMigrationMetadata.Id
        {
            get { return "202202041713346_add_unique_key_to_surveyno"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
