// <auto-generated />
namespace e_mandi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class column_added_in_orders : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(column_added_in_orders));
        
        string IMigrationMetadata.Id
        {
            get { return "202202201110317_column_added_in_orders"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
