// <auto-generated />
namespace e_mandi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class vid_added_in_orderTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(vid_added_in_orderTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202202101218004_vid_added_in_orderTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
