// <auto-generated />
namespace e_mandi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class id_name_updated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(id_name_updated));
        
        string IMigrationMetadata.Id
        {
            get { return "202202060719101_id_name_updated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
