// <auto-generated />
namespace e_mandi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class test_migration_modelBuilder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test_migration_modelBuilder));
        
        string IMigrationMetadata.Id
        {
            get { return "202202120539161_test_migration_modelBuilder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
