// <auto-generated />
namespace e_mandi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Model_builderClass_added_in_contextDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Model_builderClass_added_in_contextDb));
        
        string IMigrationMetadata.Id
        {
            get { return "202202101314129_Model_builderClass_added_in_contextDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
